[versions]
# Fabric
jdk = "25"
minecraft = "26.1.2"
fabric-loader = "0.19.2"
fabric-api = "0.146.1+26.1.2"

# Plugins
loom = "1.17-SNAPSHOT"

# Mods
baritone = "26.1-SNAPSHOT"
sodium = "mc26.1.1-0.8.9-fabric"
lithium = "mc26.1.2-0.24.2-fabric"
iris = "1.10.9+26.1-fabric"
modmenu = "18.0.0-alpha.8"
orbit = "0.2.4"
starscript = "0.2.5"
discordipc = "1.1"
reflections = "0.10.2"
netty = "4.2.7.Final"
viafabricplus = "4.5.2"
waybackauthlib = "1.1.0"

[libraries]
# Fabric
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

# Mods
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
lithium = { module = "maven.modrinth:lithium", version.ref = "lithium" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
baritone = { module = "meteordevelopment:baritone", version.ref = "baritone" }
modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }
viafabricplus = { module = "com.viaversion:viafabricplus", version.ref = "viafabricplus" }
viafabricplus-api = { module = "com.viaversion:viafabricplus-api", version.ref = "viafabricplus" }

# Libraries
orbit = { module = "meteordevelopment:orbit", version.ref = "orbit" }
starscript = { module = "org.meteordev:starscript", version.ref = "starscript" }
discord-ipc = { module = "meteordevelopment:discord-ipc", version.ref = "discordipc" }
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
netty-handler-proxy = { module = "io.netty:netty-handler-proxy", version.ref = "netty" }
netty-codec-socks = { module = "io.netty:netty-codec-socks", version.ref = "netty" }
waybackauthlib = { module = "de.florianreuth:waybackauthlib", version.ref = "waybackauthlib" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
